version: '3.8'
services:
  server:
    container_name: nodejs2022q2-server
    build:
      context: .
      dockerfile: docker/Dockerfile-web
    restart: always
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    networks:
      - app-server
    volumes:
      - logs:/app/logs
      - .:/app
    depends_on:
      - db-postgres
  db-postgres:
    container_name: nodejs2022q2-db
    build:
      context: .
      dockerfile: docker/Dockerfile-postgres
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - app-server
    volumes:
      - postgres-data:/var/lib/postgresql/data
networks:
  app-server:
    driver: bridge
    name: app-server
volumes:
  postgres-data:
  logs:
